/**
 * An exception that is created is something is thrown that isn't a Throwable.
 * This can only happen by calling C++ code that throws an uncaught exception.
 *
 * @note  The compiler can assume that no ForeignException is ever thrown.
 *   Hence, the exact handler where the exception is caught is undefined.
 *
 * @todo  really implement this correctly ensuring that the exception stack
 *   remains balanced under all circumstances
 */
public class ForeignException <: Exception, final {
    new;

    override
    def message = "caught a non-Tyr exception"
}